@startuml
skinparam shadowing false
start
:ﺭﺎﻤﯿﺑ ﺖﯾﻮﻫ ﺯﺍﺮﺣﺍ ﻭ ﺩﻭﺭﻭ;
:ﯽﻟﺎﺧ ﯼﺎﻫﺕﻼﺳﺍ ﻩﺪﻫﺎﺸﻣ ﻭ ﮏﺷﺰﭘ ﯼﻮﺠﺘﺴﺟ;
if (؟ﮏﺷﺰﭘ ﯼﺭﺎﮐ ﺯﻭﺭ) then (ﻪﻠﺑ)
  :ﯽﻟﺎﺧ ﯼﺎﻫﺕﻼﺳﺍ ﺯﺍ ﺖﻋﺎﺳ ﺏﺎﺨﺘﻧﺍ;
  if (؟ﺖﺳﺍ ﯽﻟﺎﺧ ﺕﻼﺳﺍ) then (ﻪﻠﺑ)
    :ﺪﯿﯾﺄﺗ ﺭﺎﻈﺘﻧﺍ ﺭﺩ :ﺖﯿﻌﺿﻭ — ﺖﺑﻮﻧ ﺖﺒﺛ;
    :ﻩﺪﺷﻡﺎﺠﻧﺍ ،ﺖﻣﺪﺧ ﻪﺋﺍﺭﺍ ،ﯽﻌﻄﻗ ،ﮏﺷﺰﭘ ﺪﯿﯾﺄﺗ;
    stop
  else (ﺮﯿﺧ)
    :ﺮﮕﯾﺩ ﺖﻋﺎﺳ ﺏﺎﺨﺘﻧﺍ;
  endif
else (ﺮﯿﺧ)
  :ﺮﮕﯾﺩ ﺦﯾﺭﺎﺗ ﺏﺎﺨﺘﻧﺍ;
endif
@enduml
