@startuml
skinparam shadowing false
actor "(ﺪﯾﻭﺭﺪﻧﺍ ﭖﺍ) ﺭﺎﻤﯿﺑ" as App
participant "(Spring Boot) ﯽﮐﻭﺪﺑ ﺭﻭﺮﺳ" as S
database "(PostgreSQL) ﻩﺩﺍﺩ ﻩﺎﮕﯾﺎﭘ" as DB
App -> S : ﺭﻮﺒﻋ ﺰﻣﺭ ﻭ ﻞﯿﻤﯾﺍ ﺎﺑ ﺩﻭﺭﻭ
S -> DB : BCrypt ﯽﺳﺭﺮﺑ ﻭ ﺮﺑﺭﺎﮐ ﻡﻼﻌﺘﺳﺍ
DB --> S : ﺮﺑﺭﺎﮐ ﺕﺎﻋﻼﻃﺍ
S --> App : requiresOtp ؛ OTP ﻝﺎﺳﺭﺍ
App -> S : JWT ﺖﻓﺎﯾﺭﺩ ﻭ ﺪﮐ ﺪﯿﯾﺄﺗ
App -> S : GET ﻥﺎﺘﺳﺭﺎﻤﯿﺑ / ﺺﺼﺨﺗ / ﺮﻬﺷ ﺎﺑ ﻥﺎﮑﺷﺰﭘ
S -> DB : ﻩﺪﺷﺮﺘﻠﯿﻓ ﯼﻮﺟﻭﺱﺮﭘ
DB --> App : ﺎﻫﺕﻼﺳﺍ ﻭ ﻥﺎﮑﺷﺰﭘ ﺖﺴﯿﻟ
App -> S : POST ﺖﺑﻮﻧ ﺖﺒﺛ
S -> DB : ﺪﯿﯾﺄﺗ ﺭﺎﻈﺘﻧﺍ ﺭﺩ ﺖﯿﻌﺿﻭ ﺎﺑ ﺖﺑﻮﻧ ﻩﺮﯿﺧﺫ
S --> App : (PENDING) ﻩﺪﺷﺖﺒﺛ ﺖﺑﻮﻧ
@enduml
