@startuml
skinparam shadowing false
skinparam backgroundColor #FFFFFF
skinparam actorStyle awesome
left to right direction
actor "ﺭﺎﻤﯿﺑ" as Patient
actor "ﮏﺷﺰﭘ" as Doctor
actor "ﻢﺘﺴﯿﺳ ﺮﯾﺪﻣ" as Admin
rectangle "ﯽﮐﻭﺪﺑ ﮏﺷﺰﭘ ﺖﺑﻮﻧ ﻭﺭﺯﺭ ﻪﻧﺎﻣﺎﺳ" {
  usecase "ﯼﺍﻪﻠﺣﺮﻣﻭﺩ ﺩﻭﺭﻭ ﻭ ﻡﺎﻧﺖﺒﺛ" as UC1
  usecase "ﻥﺎﮑﺷﺰﭘ ﻩﺪﻫﺎﺸﻣ ﻭ ﻮﺠﺘﺴﺟ" as UC2
  usecase "ﯽﻟﺎﺧ ﯼﺎﻫﺕﻼﺳﺍ ﻩﺪﻫﺎﺸﻣ" as UC3
  usecase "ﺪﯾﺪﺟ ﺖﺑﻮﻧ ﻭﺭﺯﺭ" as UC4
  usecase "ﺖﺑﻮﻧ ﻮﻐﻟ / ﻥﺎﻣﺯ ﺮﯿﯿﻐﺗ" as UC5
  usecase "ﻦﻣ ﯼﺎﻫﺖﺑﻮﻧ ﻩﺪﻫﺎﺸﻣ" as UC6
  usecase "ﻥﺍﺭﺎﻤﯿﺑ ﯼﺎﻫﺖﺑﻮﻧ ﻩﺪﻫﺎﺸﻣ" as UC7
  usecase "ﺖﺑﻮﻧ ﺩﺭ / ﺪﯿﯾﺄﺗ" as UC8
  usecase "ﻩﺪﺷﻡﺎﺠﻧﺍ ﺖﺑﻮﻧ ﺖﺒﺛ" as UC9
  usecase "ﮏﺷﺰﭘ ﻂﺳﻮﺗ ﺖﺑﻮﻧ ﻮﻐﻟ" as UC10
  usecase "ﮏﺷﺰﭘ ﻞﯾﺎﻓﻭﺮﭘ ﺶﯾﺍﺮﯾﻭ" as UC11
  usecase "ﮏﺷﺰﭘ ﻑﺬﺣ / ﺶﯾﺍﺮﯾﻭ / ﻥﺩﻭﺰﻓﺍ" as UC12
  usecase "ﺎﻫﺶﻘﻧ ﻭ ﻥﺍﺮﺑﺭﺎﮐ ﺖﯾﺮﯾﺪﻣ" as UC13
  usecase "ﻢﺘﺴﯿﺳ ﻞﮐ ﺭﺎﻣﺁ ﻩﺪﻫﺎﺸﻣ" as UC14
}
Patient --> UC1
Patient --> UC2
Patient --> UC3
Patient --> UC4
Patient --> UC5
Patient --> UC6
Doctor --> UC7
Doctor --> UC8
Doctor --> UC9
Doctor --> UC10
Doctor --> UC11
Admin --> UC12
Admin --> UC13
Admin --> UC14
@enduml
